### ISSUE TITLE
hslogger 1.2.7 and time 1.5.*

### ISSUE THREAD

**Issue by nikomi** [jgoerzen/hslogger#32]
Thanx for the update to hslogger supporting `time >= 1.5` !

Unfortunately there seems to be a problem regarding the dependency limits in `hslogger.cabal` causing cabal to fail with the following error:
```
trying: hslogger-1.2.7:-buildtests
rejecting: hslogger-1.2.7:+small_base (conflict: Cabal =>
time==1.5.0.1/installed-13a..., hslogger-1.2.7:small_base => time<1.5)
rejecting: hslogger-1.2.7:-small_base (conflict:
base==4.8.0.0/installed-189..., hslogger-1.2.7:small_base => base<3)
```
I believe the limit on `time < 1.5` in `hslogger.cabal` might be the culprit here.

**Comment by jgoerzen** [comment]
This was resolved in e2cb4c888e63181cfcb96b7a01ad326040e39a17 already
