### ISSUE TITLE
Syslog logger ignores message priority

### ISSUE THREAD

**Issue by DaveCTurner** [jgoerzen/hslogger#34]
Not quite true, it seems to use the message priority internally for filtering, but seems to use the _handler's_ priority in the message that goes to syslog rather than the message's priority.

A couple of lines from a `strace` output:

    5797  sendto(22, "<134>cluster[5797]: [cluster/INF"..., 56, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 56
    5800  sendto(22, "<134>cluster[5797]: [cluster/WAR"..., 105, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 1

`<134>` is `local0.info` which is correct for the first line but wrong for the second as that was sent with WARNING priority.

My handler is created with

    sysLog <- openlog "cluster" [PID] LOCAL0 INFO

If I change this to

    sysLog <- openlog "cluster" [PID] LOCAL0 DEBUG

(but change nothing else) then the messages are logged at DEBUG priority (`<135>`):

    6055  sendto(22, "<135>cluster[6055]: [cluster/INF"..., 56, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 56
    6056  sendto(22, "<135>cluster[6055]: [cluster/WAR"..., 105, 0, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 1

First noticed in 1.2.8 but still seems to be an issue in HEAD (c9433f88beac13a51f2cdf2cf0c201f39aab1a78) despite that code now looking correct.

**Comment by nd2s** [comment]
+1, major bug. Makes syslog pretty unusable.

Looking at the age of this ticket I assume this project is abandoned.
