### ISSUE TITLE
The 'buildtests' flag is redundant

### ISSUE THREAD

**Issue by peti** [jgoerzen/hslogger#40]
The Cabal flag `buildtests` duplicates the exact same functionality as the `--enable-tests` flag to `cabal`. Unless I'm missing something, I believe you could just remove that without losing any functionality.

**Comment by jgoerzen** [comment]
You are right.  That flag didn't exist when that cabal file was written.  The change was pulled as part of adf61ef9c502d2fbb8c70af0363de5ac0bf0c275

**Comment by grayjay** [comment]
Should this issue be reopened?

**Comment by peti** [comment]
Also, what is adf61ef9c502d2fbb8c70af0363de5ac0bf0c275? It's not a commit in this repository, apparently.
